#load libraries
library(phyloseq)
library(tidyverse)
library(ggplot2)
library(ggpubr)

#Load 16S Results
asv_table<-read_tsv("feaure-table.tsv",skip=1)
taxonomy<-read_tsv("taxonomy.tsv")
metadata<-read.csv("metadata_merged_NSCLC.csv")
asv_mat<-asv_table%>%column_to_rownames("#OTU ID")%>%as.matrix()
taxonomy_clean<-taxonomy%>%separate(Taxon,into=c("Kingdom","Phylum","Class","Order","Family","Genus","Species"),sep=";",fill='right')%>%column_to_rownames("Feature ID")
OTU<-otu_table(asv_mat,taxa_are_rows=TRUE)
TAX<-tax_table(as.matrix(taxonomy_clean))
META<-sample_data(metadata%>%column_to_rownames("sample.id"))

# Create phyloseq object and assign flagellin genera
ps<-phyloseq(OTU,TAX,META)
ps_rel<-transform_sample_counts(ps,function(x)x/sum(x))
df_genus <- psmelt(ps_rel) %>%group_by(Sample, Genus, Disease) %>%  summarise(Abundance = sum(Abundance), .groups = "drop")
df_genus <- df_genus %>% filter(Abundance > 0)
wilcox_results <- df_genus %>% group_by(Genus) %>% summarise( p_value = tryCatch( wilcox.test(Abundance ~ Disease)$p.value,error = function(e) NA),median_NSCLC = median(Abundance[Disease == "NSCLC"], na.rm = TRUE), median_Control = median(Abundance[Disease == "Control"], na.rm = TRUE),.groups = "drop") %>% arrange(p_value)
head(wilcox_results, 20)
flagellin_genera_detected <- c(" Herbaspirillum", " Sphingomonas"," Campylobacter",  " Stenotrophomonas", " Aquabacterium", " Phyllobacterium", " Diaphorobacter")
tax_df<-as.data.frame(tax_table(ps_rel))
tax_df$Genus_clean<-sub("g__","",tax_df$Genus)
flag_taxa<-rownames(tax_df[tax_df$Genus_clean%in%flagellin_genera_detected,])
ps_flagellin<-prune_taxa(flag_taxa,ps_rel)
ps_flagellin_genus<-tax_glom(ps_flagellin,taxrank="Genus")
df_flagellin2<-psmelt(ps_flagellin_genus)
df_flagellin2$Disease<-factor(df_flagellin2$Disease,levels=c("NSCLC","Control"))
df_sum<-df_flagellin2%>%group_by(Sample,Disease)%>%summarise(Abundance=sum(Abundance),.groups="drop")
df_sum<-df_sum%>%filter(Abundance>0)
ggplot(df_sum, aes(x = Disease, y = Abundance * 100, color = Disease)) + geom_boxplot(outlier.shape = NA, fill = NA, size = .5) +  geom_jitter(width = 0.15, alpha = 0.5, size = 2) + scale_color_manual(values = c("NSCLC" = "red", "Control" = "deepskyblue3")) +labs(y = "Relative Abundance of flagellin/bacteria (%)", x = NULL) + theme_bw(base_size = 14) +stat_compare_means(method = "wilcox.test",label = "p.format",comparisons = list(c("NSCLC", "Control"))) +theme(legend.position = "none",plot.title = element_text(hjust = 0.5),axis.text = element_text(color = "black"))
